import type { Metadata } from "next";
import "./globals.css";

import "@fontsource/sansation";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">
        <Toaster position="top-right" theme="light" /> {children}
        <div id="modal-root" />
      </body>
    </html>
  );
}
